title: ESP32 Panic Button 🚨
description: A Wi-Fi-enabled panic button with captive portal config and email alerting.
theme: just-the-docs

url: https://rahb-realtors-association.github.io/panic-button-esp/

aux_links:
  GitHub Repo: https://github.com/RAHB-REALTORS-Association/panic-button-esp
  Cornerstone Association of REALTORS®: https://www.cornerstone.inc