version: '3.8'

services:
  ota-server:
    build: .
    container_name: ota-update-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./config.json:/app/config.json
      - ./devices.json:/app/devices.json
      - ./firmware:/app/firmware
    environment:
      - OTA_SERVER_SHARED_SECRET_KEY=${OTA_SERVER_SHARED_SECRET_KEY:-your-device-secret-key}
      - OTA_SERVER_ADMIN_API_KEY=${OTA_SERVER_ADMIN_API_KEY:-change-admin-api-key-in-production}
      - OTA_SERVER_SERVER_HOST=0.0.0.0
      - OTA_SERVER_SERVER_PORT=5000
      - OTA_SERVER_LOG_LEVEL=INFO
    networks:
      - ota-network

networks:
  ota-network:
    driver: bridge